// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/devtron-labs/source-controller/api"
	"github.com/devtron-labs/source-controller/internal/logger"
	"github.com/devtron-labs/source-controller/sql"
	"github.com/devtron-labs/source-controller/sql/repo"
)

// Injectors from Wire.go:

func InitializeApp() (*App, error) {
	sugaredLogger := logger.NewSugardLogger()
	config, err := sql.GetConfig()
	if err != nil {
		return nil, err
	}
	db, err := sql.NewDbConnection(config, sugaredLogger)
	if err != nil {
		return nil, err
	}
	router := api.NewRouter(sugaredLogger)
	sourceControllerConfig, err := GetSourceControllerConfig()
	if err != nil {
		return nil, err
	}
	ciArtifactRepositoryImpl := repository.NewCiArtifactRepositoryImpl(db, sugaredLogger)
	sourceControllerServiceImpl := NewSourceControllerServiceImpl(sugaredLogger, sourceControllerConfig, ciArtifactRepositoryImpl)
	app := NewApp(sugaredLogger, db, router, sourceControllerServiceImpl)
	return app, nil
}
